version: '2.2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data-volume:/var/lib/postgresql/data

volumes:
  db-data-volume:
